name: Supabase Canlandirici

on:
  schedule:
    # Her Pazartesi ve Perşembe sabah 09:00'da çalışır
    - cron: '0 9 * * 1,4'
  workflow_dispatch: # Manuel buton

jobs:
  uyandirma_servisi:
    runs-on: ubuntu-latest
    steps:
      - name: Supabase Ping At
        # proje ID'n: eoqswyxtzfuzpyzlqeef
        run: curl -I https://eoqswyxtzfuzpyzlqeef.supabase.co
